<?php
/**
 * Dữ liệu mẫu. Giá tính bằng VNĐ; key của 'prices' và 'stock' là slug của thuộc tính Khối lượng.
 */
return array(
	'categories' => array(
		'robusta'   => 'Robusta',
		'arabica'   => 'Arabica',
		'culi'      => 'Culi',
		'blend'     => 'Blend',
		'phin-giay' => 'Phin giấy',
		'hoa-tan'   => 'Hoà tan',
	),
	'weights'    => array( '250g' => '250g', '500g' => '500g', '1kg' => '1kg' ),
	'weight_kg'  => array( '250g' => 0.25, '500g' => 0.5, '1kg' => 1.0 ),
	'grinds'     => array(
		'nguyen-hat'    => 'Nguyên hạt',
		'xay-phin'      => 'Xay phin',
		'xay-espresso'  => 'Xay espresso',
		'xay-pour-over' => 'Xay pour-over',
	),
	'products'   => array(
		array(
			'sku'         => 'CF-ROB-BMT',
			'name'        => 'Robusta Buôn Ma Thuột',
			'slug'        => 'robusta-buon-ma-thuot',
			'category'    => 'robusta',
			'type'        => 'variable',
			'prices'      => array( '250g' => 95000, '500g' => 180000, '1kg' => 340000 ),
			// 250g tồn nhiều vì test E2E mua biến thể này nhiều lần; 1kg tồn thấp để minh hoạ cảnh báo sắp hết hàng.
			'stock'       => array( '250g' => 500, '500g' => 20, '1kg' => 3 ),
			'label'       => array( 'ROBUSTA', 'Buôn Ma Thuột' ),
			'short'       => 'Robusta rang đậm, đắng sô-cô-la, hợp pha phin sữa đá.',
			'description' => 'Hạt Robusta chín đỏ từ vùng đất đỏ bazan Buôn Ma Thuột, rang đậm theo mẻ nhỏ. Thân dày, đắng rõ, hậu ngọt – đúng chất cà phê phin truyền thống.',
			'bean'        => array( 'origin' => 'Buôn Ma Thuột, Đắk Lắk', 'altitude' => '500–600m', 'roast' => 'dark', 'flavor' => 'Đậm, sô-cô-la đen, hậu ngọt' ),
		),
		array(
			'sku'         => 'CF-ROB-HONEY',
			'name'        => 'Robusta Honey Gia Lai',
			'slug'        => 'robusta-honey-gia-lai',
			'category'    => 'robusta',
			'type'        => 'variable',
			'prices'      => array( '250g' => 110000, '500g' => 210000, '1kg' => 400000 ),
			'label'       => array( 'ROBUSTA', 'Honey Gia Lai' ),
			'short'       => 'Sơ chế honey, ngọt mật ong, ít đắng.',
			'description' => 'Robusta sơ chế honey giữ lại lớp thịt quả khi phơi, cho vị ngọt mật ong và caramel, thân dày mà ít gắt.',
			'bean'        => array( 'origin' => 'Chư Sê, Gia Lai', 'altitude' => '700m', 'roast' => 'medium', 'flavor' => 'Mật ong, caramel, thân dày' ),
		),
		array(
			'sku'         => 'CF-ARA-CD',
			'name'        => 'Arabica Cầu Đất',
			'slug'        => 'arabica-cau-dat',
			'category'    => 'arabica',
			'type'        => 'variable',
			'prices'      => array( '250g' => 150000, '500g' => 290000, '1kg' => 560000 ),
			'label'       => array( 'ARABICA', 'Cầu Đất' ),
			'short'       => 'Chua thanh, thơm hoa, hợp pour-over.',
			'description' => 'Arabica trồng trên đồi Cầu Đất mát lạnh quanh năm, rang nhạt để giữ vị chua thanh của cam chanh và hương hoa trắng.',
			'bean'        => array( 'origin' => 'Cầu Đất, Lâm Đồng', 'altitude' => '1.500m', 'roast' => 'light', 'flavor' => 'Cam chanh, hoa trắng, chua thanh' ),
		),
		array(
			'sku'         => 'CF-ARA-SL',
			'name'        => 'Arabica Sơn La',
			'slug'        => 'arabica-son-la',
			'category'    => 'arabica',
			'type'        => 'variable',
			'prices'      => array( '250g' => 135000, '500g' => 260000, '1kg' => 500000 ),
			'label'       => array( 'ARABICA', 'Sơn La' ),
			'short'       => 'Vị trái cây chín, hạt dẻ, cân bằng.',
			'description' => 'Arabica vùng Tây Bắc, rang vừa cho vị trái cây chín và hạt dẻ, dễ uống cả pha phin lẫn pha máy.',
			'bean'        => array( 'origin' => 'Thuận Châu, Sơn La', 'altitude' => '1.200m', 'roast' => 'medium', 'flavor' => 'Trái cây chín, hạt dẻ' ),
		),
		array(
			'sku'         => 'CF-ARA-KS',
			'name'        => 'Arabica Khe Sanh',
			'slug'        => 'arabica-khe-sanh',
			'category'    => 'arabica',
			'type'        => 'variable',
			'prices'      => array( '250g' => 140000, '500g' => 270000, '1kg' => 520000 ),
			'label'       => array( 'ARABICA', 'Khe Sanh' ),
			'short'       => 'Sô-cô-la sữa, quả mọng, hậu dài.',
			'description' => 'Arabica từ cao nguyên Hướng Hoá, rang vừa, vị sô-cô-la sữa xen chút quả mọng.',
			'bean'        => array( 'origin' => 'Hướng Hoá, Quảng Trị', 'altitude' => '800m', 'roast' => 'medium', 'flavor' => 'Sô-cô-la sữa, quả mọng' ),
		),
		array(
			'sku'         => 'CF-CULI-ROB',
			'name'        => 'Culi Robusta',
			'slug'        => 'culi-robusta',
			'category'    => 'culi',
			'type'        => 'variable',
			'prices'      => array( '250g' => 105000, '500g' => 200000, '1kg' => 380000 ),
			'label'       => array( 'CULI', 'Robusta' ),
			'short'       => 'Hạt tròn một nhân, rất đậm, nhiều caffeine.',
			'description' => 'Culi là hạt chỉ có một nhân, được tuyển riêng. Rang đậm cho ly cà phê đặc, mạnh và thơm.',
			'bean'        => array( 'origin' => 'Đắk Lắk', 'altitude' => '500m', 'roast' => 'dark', 'flavor' => 'Rất đậm, đắng mạnh' ),
		),
		array(
			'sku'         => 'CF-CULI-ARA',
			'name'        => 'Culi Arabica',
			'slug'        => 'culi-arabica',
			'category'    => 'culi',
			'type'        => 'variable',
			'prices'      => array( '250g' => 160000, '500g' => 310000, '1kg' => 600000 ),
			'label'       => array( 'CULI', 'Arabica' ),
			'short'       => 'Đậm đà mà vẫn chua nhẹ.',
			'description' => 'Culi Arabica tuyển từ Lâm Đồng, rang vừa – đậm đà nhưng vẫn giữ được vị chua nhẹ đặc trưng của Arabica.',
			'bean'        => array( 'origin' => 'Lâm Đồng', 'altitude' => '1.400m', 'roast' => 'medium', 'flavor' => 'Đậm đà, chua nhẹ' ),
		),
		array(
			'sku'         => 'CF-BLEND-TT',
			'name'        => 'Blend Truyền Thống',
			'slug'        => 'blend-truyen-thong',
			'category'    => 'blend',
			'type'        => 'variable',
			'prices'      => array( '250g' => 99000, '500g' => 190000, '1kg' => 360000 ),
			'label'       => array( 'BLEND', 'Truyền Thống' ),
			'short'       => '70% Robusta – 30% Arabica, chuẩn vị phin sữa đá.',
			'description' => 'Phối trộn 70% Robusta Đắk Lắk và 30% Arabica Lâm Đồng, rang đậm – đậm, thơm, hợp pha phin với sữa đặc.',
			// Không có độ cao (blend nhiều vùng) – khung Thông tin hạt sẽ ẩn dòng này.
			'bean'        => array( 'origin' => 'Đắk Lắk & Lâm Đồng', 'altitude' => '', 'roast' => 'dark', 'flavor' => 'Đậm, thơm, hậu ngọt' ),
		),
		array(
			'sku'         => 'CF-BLEND-ESP',
			'name'        => 'Blend Espresso Mộc',
			'slug'        => 'blend-espresso-moc',
			'category'    => 'blend',
			'type'        => 'variable',
			'prices'      => array( '250g' => 125000, '500g' => 240000, '1kg' => 460000 ),
			'label'       => array( 'ESPRESSO', 'Blend Mộc' ),
			'short'       => 'Crema dày, sô-cô-la, caramel – cho máy pha espresso.',
			'description' => 'Blend dành cho espresso và các món có sữa: crema dày, vị sô-cô-la và caramel cân bằng.',
			'bean'        => array( 'origin' => 'Gia Lai & Lâm Đồng', 'altitude' => '', 'roast' => 'medium', 'flavor' => 'Sô-cô-la, caramel' ),
		),
		array(
			'sku'         => 'CF-PHIN-ROB',
			'name'        => 'Phin giấy Robusta (hộp 10 gói)',
			'slug'        => 'phin-giay-robusta',
			'category'    => 'phin-giay',
			'type'        => 'simple',
			'price'       => 85000,
			'stock'       => 30,
			'label'       => array( 'PHIN GIẤY', 'Hộp 10 gói' ),
			'short'       => 'Tiện mang đi làm, pha trong 3 phút.',
			'description' => 'Mỗi gói phin giấy chứa sẵn 12g Robusta xay vừa, chỉ cần treo lên cốc và rót nước sôi.',
			'bean'        => array( 'origin' => 'Buôn Ma Thuột, Đắk Lắk', 'roast' => 'dark' ),
		),
		array(
			'sku'         => 'CF-PHIN-ARA',
			'name'        => 'Phin giấy Arabica (hộp 10 gói)',
			'slug'        => 'phin-giay-arabica',
			'category'    => 'phin-giay',
			'type'        => 'simple',
			'price'       => 110000,
			'stock'       => 4, // Tồn thấp để minh hoạ cảnh báo sắp hết hàng.
			'label'       => array( 'PHIN GIẤY', 'Arabica' ),
			'short'       => 'Arabica pha nhanh, chua thanh dễ chịu.',
			'description' => 'Phin giấy Arabica Cầu Đất – hương thơm nhẹ, chua thanh, pha nhanh ở bất cứ đâu.',
			'bean'        => array( 'origin' => 'Cầu Đất, Lâm Đồng', 'roast' => 'light' ),
		),
		array(
			'sku'         => 'CF-HT-3IN1',
			'name'        => 'Cà phê hoà tan 3in1 (hộp 20 gói)',
			'slug'        => 'ca-phe-hoa-tan-3in1',
			'category'    => 'hoa-tan',
			'type'        => 'simple',
			'price'       => 65000,
			'stock'       => 40,
			'label'       => array( 'HOÀ TAN', '3in1' ),
			'short'       => 'Cà phê, đường, bột kem – chỉ cần thêm nước nóng.',
			'description' => 'Hộp 20 gói cà phê hoà tan 3in1, vị cân bằng, tiện cho văn phòng.',
			'bean'        => array(), // Không có thông tin hạt – khung sẽ ẩn hoàn toàn.
		),
	),
);
